### ISSUE TITLE
About istio tcp source ip preserve

### ISSUE THREAD

**Issue by keyboardfann** [hzxuzhonghu/istio-demo#1]
Hi, I have read your sharing in istio conference and have need to use tcp source ip preserve.  Before follow your sharing, pgbouncer log always show 127.0.0.1.

After follow your sharing to config it. When I test it, always get the istio ingress pod ip , not the source ip. Is there anything missing or wrong?

===========================================================================
ELB target group use ip target group and enable proxy protocol v2
![image](https://user-images.githubusercontent.com/1110451/124882807-545f7d80-e003-11eb-9f55-a9898ac1beb4.png)

workflow
![image](https://user-images.githubusercontent.com/1110451/124885590-013afa00-e006-11eb-8d98-0d4738f447c9.png)

Istio 1.9.1 config
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: gcr.io/istio-release
  tag: 1.9.1
  revision: 1-9-1
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:    
	- name: internal-istio-ingressgateway
      enabled: true
      k8s:
        env:
           - name: ISTIO_META_ROUTER_MODE
             value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
            - resource:
                name: memory
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: internal-istio-ingressgateway
        overlays:
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: Deployment
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
              - path: spec.template.metadata.labels.app
                value: internal-istio-ingressgateway
              - path: spec.template.metadata.labels.istio
                value: internal-ingressgateway
          - kind: Service
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.app
                value: internal-istio-ingressgateway
              - path: spec.selector.istio
                value: internal-ingressgateway
              - path: spec.type
                value: LoadBalancer
          - kind: PodDisruptionBudget
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1500Mi
          requests:
            cpu: 300m
            memory: 256Mi
        service:
          externalTrafficPolicy: Local
          ports:
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            ## Custom port ##
            - name: pgbouncer
              port: 5432
              protocol: TCP
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-name: "internalistioingress"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
```

EnvoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 1
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: internalingress-proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: internal-ingressgateway
```

pgbouncer deployment
```
apiVersion: apps/v1
kind: Deployment
...
...
      annotations:
        sidecar.istio.io/interceptionMode: TPROXY
...
...
```

# Test #
centos 
```
[root@centos-84b59fcb69-mjbqd /]# psql -h xxxxx -U postgres -d postgres
Password for user postgres: 
psql (10.17, server )
Type "help" for help.

postgres=>
```

pgbouncer log , always show internal ingress pod ip . not source ip.
```
2021-07-08 07:46:48.981 UTC [1] LOG C-0x5642cef80e20: postgres/postgres@10.2.6.207:60467 login attempt: db=postgres user=postgres tls=no
```

**Comment by keyboardfann** [comment]
Also try your example in https://github.com/hzxuzhonghu/istio-demo/tree/main/istiocon-2021/tcp . And it donesn't through internal NLB, so it can get the right source IP.

without sidecar.istio.io/interceptionMode: TPROXY
```
[root@centos-84b59fcb69-mjbqd /]#  curl httpbin.default:8000/ip
{
  "origin": "127.0.0.1"
}
```

with sidecar.istio.io/interceptionMode: TPROXY
```
[root@centos-84b59fcb69-mjbqd /]#  curl httpbin.default:8000/ip
{
  "origin": "10.2.6.77"
}
```

**Comment by keyboardfann** [comment]
Testing through Internal ingress gateway

gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-tcp-gateway
spec:
  selector:
    istio: internal-ingressgateway
  servers:
    - port:
        number: 9999
        name: tcp
        protocol: TCP
      hosts:
      - "test.nxd.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-tcp
spec:
  hosts:
  - "test.nxd.net"
  gateways:
  - httpbin-tcp-gateway
  tcp:
    - match:
      - port: 9999
      route:
      - destination:
           host: httpbin
           port:
              number: 8000
```

Test, will show internal ingress pod ip.... not the src ip.
```
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
```
